In [1]:
import pandas as pd

misconception_mapping = pd.read_csv("./data/misconception_mapping.csv")

labels = misconception_mapping['MisconceptionName'].values
labels

array(['Does not know that angles in a triangle sum to 180 degrees',
       'Uses dividing fractions method for multiplying fractions',
       'Believes there are 100 degrees in a full turn', ...,
       'Believes that any percentage of a larger number will be greater than any percentage of a smaller number',
       'Believes a cubic expression should have three terms',
       'Misunderstands order of operations in algebraic expressions'],
      dtype=object)

In [2]:
train = pd.read_csv("./data/train.csv")

train.head()

,QuestionId,ConstructId,ConstructName,SubjectId,SubjectName,CorrectAnswer,QuestionText,AnswerAText,AnswerBText,AnswerCText,AnswerDText,MisconceptionAId,MisconceptionBId,MisconceptionCId,MisconceptionDId
0,0,856,Use the order of operations to carry out calcu...,33,BIDMAS,A,\[\n3 \times 2+4-5\n\]\nWhere do the brackets ...,\( 3 \times(2+4)-5 \),\( 3 \times 2+(4-5) \),\( 3 \times(2+4-5) \),Does not need brackets,NaN,NaN,NaN,1672.0
1,1,1612,Simplify an algebraic fraction by factorising ...,1077,Simplifying Algebraic Fractions,D,"Simplify the following, if possible: \( \frac{...",\( m+1 \),\( m+2 \),\( m-1 \),Does not simplify,2142.0,143.0,2142.0,NaN
2,2,2774,Calculate the range from a list of data,339,Range and Interquartile Range from a List of Data,B,Tom and Katie are discussing the \( 5 \) plant...,Only\nTom,Only\nKatie,Both Tom and Katie,Neither is correct,1287.0,NaN,1287.0,1073.0
3,3,2377,Recall and use the intersecting diagonals prop...,88,Properties of Quadrilaterals,C,The angles highlighted on this rectangle with ...,acute,obtuse,\( 90^{\circ} \),Not enough information,1180.0,1180.0,NaN,1180.0
4,4,3387,Substitute positive integer values into formul...,67,Substitution into Formula,A,The equation \( f=3 r^{2}+3 \) is used to find...,\( 30 \),\( 27 \),\( 51 \),\( 24 \),NaN,NaN,NaN,1818.0

In [3]:
print(train['ConstructName'].nunique())
print(train['SubjectName'].nunique())

757
163

In [ ]:
id_columns = ['MisconceptionAId', 'MisconceptionBId', 'MisconceptionCId', 'MisconceptionDId']

empty_counts = {}
for col in id_columns:
    empty_count = train[col].isna().sum()
    empty_counts[col] = empty_count

print("各欄位空值數量：")
for col, count in empty_counts.items():
    print(f"{col}: {count} 個空值")

total_empty = sum(empty_counts.values())
print(f"\n四個欄位總共有 {total_empty} 個空值")

各欄位空值數量：
MisconceptionAId: 734 個空值
MisconceptionBId: 751 個空值
MisconceptionCId: 789 個空值
MisconceptionDId: 832 個空值

四個欄位總共有 3106 個空值

In [12]:
id_columns = ['MisconceptionAId', 'MisconceptionBId', 'MisconceptionCId', 'MisconceptionDId']

id_counts = {}
for col in id_columns:
    col_counts = train[col].value_counts()
    
    for id_val, count in col_counts.items():
        if pd.notna(id_val):
            if id_val not in id_counts:
                id_counts[id_val] = count
            else:
                id_counts[id_val] += count

max_occurrences = max(id_counts.values()) if id_counts else 0

id_categories = {
    f'出現{i}次': [] for i in range(1, max_occurrences + 1)
}
id_categories['從未出現'] = set(range(2569)) - set(id_counts.keys())

for id_val, count in id_counts.items():
    id_categories[f'出現{count}次'].append(id_val)

for category, ids in id_categories.items():
    print(f"{category}: {len(ids)} 個 ID")

出現1次: 747 個 ID
出現2次: 343 個 ID
出現3次: 190 個 ID
出現4次: 109 個 ID
出現5次: 64 個 ID
出現6次: 43 個 ID
出現7次: 26 個 ID
出現8次: 17 個 ID
出現9次: 10 個 ID
出現10次: 7 個 ID
出現11次: 6 個 ID
出現12次: 9 個 ID
出現13次: 4 個 ID
出現14次: 6 個 ID
出現15次: 1 個 ID
出現16次: 4 個 ID
出現17次: 1 個 ID
出現18次: 2 個 ID
出現19次: 3 個 ID
出現20次: 1 個 ID
出現21次: 0 個 ID
出現22次: 3 個 ID
出現23次: 0 個 ID
出現24次: 0 個 ID
出現25次: 0 個 ID
出現26次: 0 個 ID
出現27次: 2 個 ID
出現28次: 0 個 ID
出現29次: 0 個 ID
出現30次: 0 個 ID
出現31次: 0 個 ID
出現32次: 1 個 ID
出現33次: 1 個 ID
出現34次: 0 個 ID
出現35次: 0 個 ID
出現36次: 1 個 ID
出現37次: 0 個 ID
出現38次: 1 個 ID
出現39次: 0 個 ID
出現40次: 0 個 ID
出現41次: 0 個 ID
出現42次: 0 個 ID
出現43次: 1 個 ID
出現44次: 0 個 ID
出現45次: 0 個 ID
出現46次: 0 個 ID
出現47次: 0 個 ID
出現48次: 0 個 ID
出現49次: 0 個 ID
出現50次: 0 個 ID
出現51次: 0 個 ID
出現52次: 0 個 ID
出現53次: 0 個 ID
出現54次: 1 個 ID
從未出現: 975 個 ID